blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/NoobforAl/blog/discussions
    about: Please ask questions and general discussions in the Discussions section
